### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by katieb1** [UBC-MDS/Rmagine#1]
Outline the package to be built, including:

- [x]  high-level summary paragraph

- [x]  bulleted list of functions + short description for each function

- [x] paragraph describing where packages fit into R ecosystem

- [ ] Edits from collaborators

**Comment by brendoncampbell** [comment]
@katieb1 @Sukriti1312 @trevorkwan feel free to update your function description and add/update any other details in the README as you see fit
